---
 - name: copy xmonad and xmobar binaries
   become: yes
   copy:
     src: "/home/{{ my_username }}/.local/bin/{{ item }}"
     dest: "/usr/local/bin/{{ item }}"
     owner: root
     group: root
     mode: 0755
     force: yes
   with_items:
     - xmonad
     - xmobar
   tags: xmonad

