---
 - name: check if packer (packer.io) exists
   stat: path=/opt/packer
   register: packer
   tags: utils

 - name: install packer (packer.io)
   script: scripts/packer.sh 0.8.1
   when: not packer.stat.exists
   tags: utils

