---
- name: link wallpaper
  file:
    src: "/home/{{ my_username }}/gfx/Wallpapers/240833_481642385188230_2001025674_o.jpg"
    dest: "/home/{{ my_username }}/gfx/wallpaper.jpg"
    state: link
    force: yes
  tags: ui

- name: link greeter style
  become: yes
  file:
    src: /usr/share/lightdm-another-gtk-greeter/themes/alien-orange2
    dest: /usr/share/lightdm-another-gtk-greeter/themes/current
    state: link
    force: yes
  tags: ui

