---
 - name: install wifi driver
   become: yes
   become_user: "root"
   environment:
     SUDO_USER: "root"
   makepkg:
     name: broadcom-wl-dkms
     state: present
     build_dir: /tmp
   tags: wifi

